# Generated by Django 2.2.5 on 2019-10-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(default='DEFAULT VALUE', primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
