# Generated by Django 2.2.5 on 2019-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191001_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='creater_name',
            field=models.ManyToManyField(related_name='creater_name', to='webapp.Admin'),
        ),
    ]
