# Generated by Django 2.2.5 on 2019-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191001_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(default='DEFAULT VALUE', primary_key=True, serialize=False),
        ),
    ]
