# Generated by Django 2.2.5 on 2019-10-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191001_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='creater_name',
        ),
    ]
